version: '3'
services:
  autopus:
    container_name: autopus
    build:
      context: .
      dockerfile: Dockerfile.integration
    ports:
      - "8088:8080"
    environment:
      AUTOPUS_MYSQL_DATASOURCE: auth:password@tcp(mysql:3306)/your_database?parseTime=true
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: auth
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"